name: CI series-2

on:
  push:
  pull_request:

jobs: 
  job1:
    runs-on: ubuntu-latest

    # STEP OUTPUTS
    steps: 
      - name: Set Output
        id: 1
        run: echo "value=42" >> $GITHUB_OUTPUT

      - name: Use Output
        id: 2
        run: echo "{{ steps.step1.outputs.value }}"

  job2:
    runs-on: ubuntu-latest

    outputs: 
      version: ${{ steps.v.outputs.version }}
    steps:
      - name: 
        id: v
        run: echo "version=1.0.0" >> $GITHUB_OUTPUT

      - name:
        id: 2
        run:

      
