name: CI series-2

on:
  push:
  pull_request:

jobs: 
  job1:
    runs-on: ubuntu-latest

    # STEP OUTPUTS
    steps: 
      - name: Set Output
        id: a
        run: echo "value=42" >> $GITHUB_OUTPUT

      - name: Use Output
        id: b
        run: echo "{{ steps.a.outputs.value }}"

  build:
    runs-on: ubuntu-latest

    outputs: 
      version: ${{ steps.v.outputs.version }}
    steps:
      - name: 
        id: v
        run: echo "version=1.0.0" >> $GITHUB_OUTPUT

  deploy:
    needs: build
    runs-on: ubuntu-latest 
      
    steps: 
      - name: Use build variables
        run: echo "${{ needs.build.outputs.version }}"