name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Verify lockfile exists
        run: ls -la package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Verify Typescript is installed
        run: npm ls typescript

      - name: Type check
        run: npx tsc --noEmit